version: '3.3'

services:
  elastic:
    restart: always
    # image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    image: elasticsearch:${STACK_VERSION}
    container_name: elastic
    volumes:
      - ./docker/config/usr/share/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:9200
    environment:
      - LICENSE=${LICENSE}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - backend

  kibana:
    restart: always
    # image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    image: kibana:${STACK_VERSION}
    container_name: kibana
    volumes:
      - ./docker/config/usr/share/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana-data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - KIBANA_USERNAME=${KIBANA_USERNAME}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - elastic
    networks:
      - backend

volumes:
  elastic-data:
  kibana-data:

networks:
  backend:
    driver: bridge
